name: Build
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            arch: x86_64
          - os: linux
            arch: aarch64
          - os: windows
            arch: x86_64
          - os: android
            arch: universal
          - os: macos
            arch: universal
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies for cross-compiling
      if: ${{ matrix.platform.arch != 'x86_64' && matrix.platform.os == 'linux' }}
      run: sudo apt -y update && sudo apt -y install qemu-user-static binfmt-support

    - name: Restore Docker cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: path/to/dependencies
        key: ${{ matrix.platform.os }}-${{ matrix.platform.arch }}

    - name: Build Docker image
      run: |
        cd docker/${{ matrix.platform.os }}
        docker build --build-arg ARCH=${{ matrix.platform.arch }} -t vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }} .

    - name: Run Docker container
      run: |
        docker run -v "${{ github.workspace }}:/vanilla" -v "${{ github.workspace }}/build:/install" -e ANDROID_SIGNING_KEY=${{ secrets.ANDROID_SIGNING_KEY }} vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}

    - name: Archive
      run: |
        tar czf vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz -C "${{ github.workspace }}/build" .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.os }} ${{ matrix.platform.arch }}
        path: vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz

    - name: Upload Continuous Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'vanilla-wiiu/vanilla' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz

